// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.1
// source: event-outgoing.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncAccountEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityID uint64 `protobuf:"varint,1,opt,name=entityID,proto3" json:"entityID,omitempty"`
	Source   string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *SyncAccountEvent) Reset() {
	*x = SyncAccountEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_outgoing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncAccountEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAccountEvent) ProtoMessage() {}

func (x *SyncAccountEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_outgoing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAccountEvent.ProtoReflect.Descriptor instead.
func (*SyncAccountEvent) Descriptor() ([]byte, []int) {
	return file_event_outgoing_proto_rawDescGZIP(), []int{0}
}

func (x *SyncAccountEvent) GetEntityID() uint64 {
	if x != nil {
		return x.EntityID
	}
	return 0
}

func (x *SyncAccountEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type AccountCreatedByEmail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityID uint64 `protobuf:"varint,1,opt,name=entityID,proto3" json:"entityID,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Language string `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
}

func (x *AccountCreatedByEmail) Reset() {
	*x = AccountCreatedByEmail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_outgoing_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountCreatedByEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountCreatedByEmail) ProtoMessage() {}

func (x *AccountCreatedByEmail) ProtoReflect() protoreflect.Message {
	mi := &file_event_outgoing_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountCreatedByEmail.ProtoReflect.Descriptor instead.
func (*AccountCreatedByEmail) Descriptor() ([]byte, []int) {
	return file_event_outgoing_proto_rawDescGZIP(), []int{1}
}

func (x *AccountCreatedByEmail) GetEntityID() uint64 {
	if x != nil {
		return x.EntityID
	}
	return 0
}

func (x *AccountCreatedByEmail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AccountCreatedByEmail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountCreatedByEmail) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type AccountCreatedByTel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityID uint64 `protobuf:"varint,1,opt,name=entityID,proto3" json:"entityID,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Tel      string `protobuf:"bytes,4,opt,name=tel,proto3" json:"tel,omitempty"`
	Language string `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
}

func (x *AccountCreatedByTel) Reset() {
	*x = AccountCreatedByTel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_outgoing_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountCreatedByTel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountCreatedByTel) ProtoMessage() {}

func (x *AccountCreatedByTel) ProtoReflect() protoreflect.Message {
	mi := &file_event_outgoing_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountCreatedByTel.ProtoReflect.Descriptor instead.
func (*AccountCreatedByTel) Descriptor() ([]byte, []int) {
	return file_event_outgoing_proto_rawDescGZIP(), []int{2}
}

func (x *AccountCreatedByTel) GetEntityID() uint64 {
	if x != nil {
		return x.EntityID
	}
	return 0
}

func (x *AccountCreatedByTel) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AccountCreatedByTel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountCreatedByTel) GetTel() string {
	if x != nil {
		return x.Tel
	}
	return ""
}

func (x *AccountCreatedByTel) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type AccountCreated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityID      uint64 `protobuf:"varint,1,opt,name=entityID,proto3" json:"entityID,omitempty"`
	Email         string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Tel           string `protobuf:"bytes,4,opt,name=tel,proto3" json:"tel,omitempty"`
	Dob           string `protobuf:"bytes,5,opt,name=dob,proto3" json:"dob,omitempty"`
	FirstName     string `protobuf:"bytes,6,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName      string `protobuf:"bytes,7,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Gender        int32  `protobuf:"varint,8,opt,name=gender,proto3" json:"gender,omitempty"`
	Address       string `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	Ward          string `protobuf:"bytes,10,opt,name=ward,proto3" json:"ward,omitempty"`
	District      string `protobuf:"bytes,11,opt,name=district,proto3" json:"district,omitempty"`
	City          string `protobuf:"bytes,12,opt,name=city,proto3" json:"city,omitempty"`
	Region        string `protobuf:"bytes,13,opt,name=region,proto3" json:"region,omitempty"`
	Country       string `protobuf:"bytes,14,opt,name=country,proto3" json:"country,omitempty"`
	Avatar        string `protobuf:"bytes,15,opt,name=avatar,proto3" json:"avatar,omitempty"`
	TelVerified   bool   `protobuf:"varint,16,opt,name=telVerified,proto3" json:"telVerified,omitempty"`
	EmailVerified bool   `protobuf:"varint,17,opt,name=emailVerified,proto3" json:"emailVerified,omitempty"`
	Created       string `protobuf:"bytes,18,opt,name=created,proto3" json:"created,omitempty"`
	Updated       string `protobuf:"bytes,19,opt,name=updated,proto3" json:"updated,omitempty"`
	Language      string `protobuf:"bytes,20,opt,name=language,proto3" json:"language,omitempty"`
	OneID         string `protobuf:"bytes,21,opt,name=oneID,proto3" json:"oneID,omitempty"`
	Active        bool   `protobuf:"varint,22,opt,name=active,proto3" json:"active,omitempty"`
	Metadata      string `protobuf:"bytes,23,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *AccountCreated) Reset() {
	*x = AccountCreated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_outgoing_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountCreated) ProtoMessage() {}

func (x *AccountCreated) ProtoReflect() protoreflect.Message {
	mi := &file_event_outgoing_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountCreated.ProtoReflect.Descriptor instead.
func (*AccountCreated) Descriptor() ([]byte, []int) {
	return file_event_outgoing_proto_rawDescGZIP(), []int{3}
}

func (x *AccountCreated) GetEntityID() uint64 {
	if x != nil {
		return x.EntityID
	}
	return 0
}

func (x *AccountCreated) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AccountCreated) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountCreated) GetTel() string {
	if x != nil {
		return x.Tel
	}
	return ""
}

func (x *AccountCreated) GetDob() string {
	if x != nil {
		return x.Dob
	}
	return ""
}

func (x *AccountCreated) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *AccountCreated) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *AccountCreated) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *AccountCreated) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AccountCreated) GetWard() string {
	if x != nil {
		return x.Ward
	}
	return ""
}

func (x *AccountCreated) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *AccountCreated) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *AccountCreated) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AccountCreated) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *AccountCreated) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *AccountCreated) GetTelVerified() bool {
	if x != nil {
		return x.TelVerified
	}
	return false
}

func (x *AccountCreated) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *AccountCreated) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *AccountCreated) GetUpdated() string {
	if x != nil {
		return x.Updated
	}
	return ""
}

func (x *AccountCreated) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *AccountCreated) GetOneID() string {
	if x != nil {
		return x.OneID
	}
	return ""
}

func (x *AccountCreated) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *AccountCreated) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type AccountUpdated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityID      uint64 `protobuf:"varint,1,opt,name=entityID,proto3" json:"entityID,omitempty"`
	Email         string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Tel           string `protobuf:"bytes,4,opt,name=tel,proto3" json:"tel,omitempty"`
	Dob           string `protobuf:"bytes,5,opt,name=dob,proto3" json:"dob,omitempty"`
	FirstName     string `protobuf:"bytes,6,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName      string `protobuf:"bytes,7,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Gender        int32  `protobuf:"varint,8,opt,name=gender,proto3" json:"gender,omitempty"`
	Address       string `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	Ward          string `protobuf:"bytes,10,opt,name=ward,proto3" json:"ward,omitempty"`
	District      string `protobuf:"bytes,11,opt,name=district,proto3" json:"district,omitempty"`
	City          string `protobuf:"bytes,12,opt,name=city,proto3" json:"city,omitempty"`
	Region        string `protobuf:"bytes,13,opt,name=region,proto3" json:"region,omitempty"`
	Country       string `protobuf:"bytes,14,opt,name=country,proto3" json:"country,omitempty"`
	Avatar        string `protobuf:"bytes,15,opt,name=avatar,proto3" json:"avatar,omitempty"`
	TelVerified   bool   `protobuf:"varint,16,opt,name=telVerified,proto3" json:"telVerified,omitempty"`
	EmailVerified bool   `protobuf:"varint,17,opt,name=emailVerified,proto3" json:"emailVerified,omitempty"`
	Created       string `protobuf:"bytes,18,opt,name=created,proto3" json:"created,omitempty"`
	Updated       string `protobuf:"bytes,19,opt,name=updated,proto3" json:"updated,omitempty"`
	Language      string `protobuf:"bytes,20,opt,name=language,proto3" json:"language,omitempty"`
	OneID         string `protobuf:"bytes,21,opt,name=oneID,proto3" json:"oneID,omitempty"`
	Active        bool   `protobuf:"varint,22,opt,name=active,proto3" json:"active,omitempty"`
	Metadata      string `protobuf:"bytes,23,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *AccountUpdated) Reset() {
	*x = AccountUpdated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_outgoing_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountUpdated) ProtoMessage() {}

func (x *AccountUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_event_outgoing_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountUpdated.ProtoReflect.Descriptor instead.
func (*AccountUpdated) Descriptor() ([]byte, []int) {
	return file_event_outgoing_proto_rawDescGZIP(), []int{4}
}

func (x *AccountUpdated) GetEntityID() uint64 {
	if x != nil {
		return x.EntityID
	}
	return 0
}

func (x *AccountUpdated) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AccountUpdated) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountUpdated) GetTel() string {
	if x != nil {
		return x.Tel
	}
	return ""
}

func (x *AccountUpdated) GetDob() string {
	if x != nil {
		return x.Dob
	}
	return ""
}

func (x *AccountUpdated) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *AccountUpdated) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *AccountUpdated) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *AccountUpdated) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AccountUpdated) GetWard() string {
	if x != nil {
		return x.Ward
	}
	return ""
}

func (x *AccountUpdated) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *AccountUpdated) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *AccountUpdated) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AccountUpdated) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *AccountUpdated) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *AccountUpdated) GetTelVerified() bool {
	if x != nil {
		return x.TelVerified
	}
	return false
}

func (x *AccountUpdated) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *AccountUpdated) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *AccountUpdated) GetUpdated() string {
	if x != nil {
		return x.Updated
	}
	return ""
}

func (x *AccountUpdated) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *AccountUpdated) GetOneID() string {
	if x != nil {
		return x.OneID
	}
	return ""
}

func (x *AccountUpdated) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *AccountUpdated) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type PhoneLinked struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityID uint64 `protobuf:"varint,1,opt,name=entityID,proto3" json:"entityID,omitempty"`
	Tel      string `protobuf:"bytes,2,opt,name=tel,proto3" json:"tel,omitempty"`
}

func (x *PhoneLinked) Reset() {
	*x = PhoneLinked{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_outgoing_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhoneLinked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneLinked) ProtoMessage() {}

func (x *PhoneLinked) ProtoReflect() protoreflect.Message {
	mi := &file_event_outgoing_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneLinked.ProtoReflect.Descriptor instead.
func (*PhoneLinked) Descriptor() ([]byte, []int) {
	return file_event_outgoing_proto_rawDescGZIP(), []int{5}
}

func (x *PhoneLinked) GetEntityID() uint64 {
	if x != nil {
		return x.EntityID
	}
	return 0
}

func (x *PhoneLinked) GetTel() string {
	if x != nil {
		return x.Tel
	}
	return ""
}

type PhoneVerified struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityID uint64 `protobuf:"varint,1,opt,name=entityID,proto3" json:"entityID,omitempty"`
	Tel      string `protobuf:"bytes,2,opt,name=tel,proto3" json:"tel,omitempty"`
}

func (x *PhoneVerified) Reset() {
	*x = PhoneVerified{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_outgoing_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhoneVerified) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneVerified) ProtoMessage() {}

func (x *PhoneVerified) ProtoReflect() protoreflect.Message {
	mi := &file_event_outgoing_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneVerified.ProtoReflect.Descriptor instead.
func (*PhoneVerified) Descriptor() ([]byte, []int) {
	return file_event_outgoing_proto_rawDescGZIP(), []int{6}
}

func (x *PhoneVerified) GetEntityID() uint64 {
	if x != nil {
		return x.EntityID
	}
	return 0
}

func (x *PhoneVerified) GetTel() string {
	if x != nil {
		return x.Tel
	}
	return ""
}

type LanguageUpdated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityID uint64 `protobuf:"varint,1,opt,name=entityID,proto3" json:"entityID,omitempty"`
	Language string `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
}

func (x *LanguageUpdated) Reset() {
	*x = LanguageUpdated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_outgoing_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LanguageUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguageUpdated) ProtoMessage() {}

func (x *LanguageUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_event_outgoing_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguageUpdated.ProtoReflect.Descriptor instead.
func (*LanguageUpdated) Descriptor() ([]byte, []int) {
	return file_event_outgoing_proto_rawDescGZIP(), []int{7}
}

func (x *LanguageUpdated) GetEntityID() uint64 {
	if x != nil {
		return x.EntityID
	}
	return 0
}

func (x *LanguageUpdated) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type AccountRegisteredByTel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityID uint64 `protobuf:"varint,1,opt,name=EntityID,proto3" json:"EntityID,omitempty"`
	Tel      string `protobuf:"bytes,2,opt,name=tel,proto3" json:"tel,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Language string `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
}

func (x *AccountRegisteredByTel) Reset() {
	*x = AccountRegisteredByTel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_outgoing_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountRegisteredByTel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRegisteredByTel) ProtoMessage() {}

func (x *AccountRegisteredByTel) ProtoReflect() protoreflect.Message {
	mi := &file_event_outgoing_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRegisteredByTel.ProtoReflect.Descriptor instead.
func (*AccountRegisteredByTel) Descriptor() ([]byte, []int) {
	return file_event_outgoing_proto_rawDescGZIP(), []int{8}
}

func (x *AccountRegisteredByTel) GetEntityID() uint64 {
	if x != nil {
		return x.EntityID
	}
	return 0
}

func (x *AccountRegisteredByTel) GetTel() string {
	if x != nil {
		return x.Tel
	}
	return ""
}

func (x *AccountRegisteredByTel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountRegisteredByTel) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type AccountDeleted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityID uint64 `protobuf:"varint,1,opt,name=EntityID,proto3" json:"EntityID,omitempty"`
}

func (x *AccountDeleted) Reset() {
	*x = AccountDeleted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_outgoing_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountDeleted) ProtoMessage() {}

func (x *AccountDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_event_outgoing_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountDeleted.ProtoReflect.Descriptor instead.
func (*AccountDeleted) Descriptor() ([]byte, []int) {
	return file_event_outgoing_proto_rawDescGZIP(), []int{9}
}

func (x *AccountDeleted) GetEntityID() uint64 {
	if x != nil {
		return x.EntityID
	}
	return 0
}

type AccountDeactivateRequested struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountID uint64 `protobuf:"varint,1,opt,name=AccountID,proto3" json:"AccountID,omitempty"`
}

func (x *AccountDeactivateRequested) Reset() {
	*x = AccountDeactivateRequested{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_outgoing_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountDeactivateRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountDeactivateRequested) ProtoMessage() {}

func (x *AccountDeactivateRequested) ProtoReflect() protoreflect.Message {
	mi := &file_event_outgoing_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountDeactivateRequested.ProtoReflect.Descriptor instead.
func (*AccountDeactivateRequested) Descriptor() ([]byte, []int) {
	return file_event_outgoing_proto_rawDescGZIP(), []int{10}
}

func (x *AccountDeactivateRequested) GetAccountID() uint64 {
	if x != nil {
		return x.AccountID
	}
	return 0
}

type AccountDeactivated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountID uint64 `protobuf:"varint,1,opt,name=AccountID,proto3" json:"AccountID,omitempty"`
}

func (x *AccountDeactivated) Reset() {
	*x = AccountDeactivated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_outgoing_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountDeactivated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountDeactivated) ProtoMessage() {}

func (x *AccountDeactivated) ProtoReflect() protoreflect.Message {
	mi := &file_event_outgoing_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountDeactivated.ProtoReflect.Descriptor instead.
func (*AccountDeactivated) Descriptor() ([]byte, []int) {
	return file_event_outgoing_proto_rawDescGZIP(), []int{11}
}

func (x *AccountDeactivated) GetAccountID() uint64 {
	if x != nil {
		return x.AccountID
	}
	return 0
}

type AccountActivated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountID uint64 `protobuf:"varint,1,opt,name=AccountID,proto3" json:"AccountID,omitempty"`
}

func (x *AccountActivated) Reset() {
	*x = AccountActivated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_outgoing_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountActivated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountActivated) ProtoMessage() {}

func (x *AccountActivated) ProtoReflect() protoreflect.Message {
	mi := &file_event_outgoing_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountActivated.ProtoReflect.Descriptor instead.
func (*AccountActivated) Descriptor() ([]byte, []int) {
	return file_event_outgoing_proto_rawDescGZIP(), []int{12}
}

func (x *AccountActivated) GetAccountID() uint64 {
	if x != nil {
		return x.AccountID
	}
	return 0
}

type TaskDeactivatedAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountID uint64 `protobuf:"varint,1,opt,name=accountID,proto3" json:"accountID,omitempty"`
	Expire    string `protobuf:"bytes,2,opt,name=expire,proto3" json:"expire,omitempty"`
}

func (x *TaskDeactivatedAccount) Reset() {
	*x = TaskDeactivatedAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_outgoing_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskDeactivatedAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDeactivatedAccount) ProtoMessage() {}

func (x *TaskDeactivatedAccount) ProtoReflect() protoreflect.Message {
	mi := &file_event_outgoing_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDeactivatedAccount.ProtoReflect.Descriptor instead.
func (*TaskDeactivatedAccount) Descriptor() ([]byte, []int) {
	return file_event_outgoing_proto_rawDescGZIP(), []int{13}
}

func (x *TaskDeactivatedAccount) GetAccountID() uint64 {
	if x != nil {
		return x.AccountID
	}
	return 0
}

func (x *TaskDeactivatedAccount) GetExpire() string {
	if x != nil {
		return x.Expire
	}
	return ""
}

type TaskNotificationDeleteAccountAfter30Days struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountID uint64 `protobuf:"varint,1,opt,name=accountID,proto3" json:"accountID,omitempty"`
	Expire    string `protobuf:"bytes,2,opt,name=expire,proto3" json:"expire,omitempty"`
}

func (x *TaskNotificationDeleteAccountAfter30Days) Reset() {
	*x = TaskNotificationDeleteAccountAfter30Days{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_outgoing_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskNotificationDeleteAccountAfter30Days) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskNotificationDeleteAccountAfter30Days) ProtoMessage() {}

func (x *TaskNotificationDeleteAccountAfter30Days) ProtoReflect() protoreflect.Message {
	mi := &file_event_outgoing_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskNotificationDeleteAccountAfter30Days.ProtoReflect.Descriptor instead.
func (*TaskNotificationDeleteAccountAfter30Days) Descriptor() ([]byte, []int) {
	return file_event_outgoing_proto_rawDescGZIP(), []int{14}
}

func (x *TaskNotificationDeleteAccountAfter30Days) GetAccountID() uint64 {
	if x != nil {
		return x.AccountID
	}
	return 0
}

func (x *TaskNotificationDeleteAccountAfter30Days) GetExpire() string {
	if x != nil {
		return x.Expire
	}
	return ""
}

type TaskNotificationDeleteAccountAfter24Hours struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountID uint64 `protobuf:"varint,1,opt,name=accountID,proto3" json:"accountID,omitempty"`
	Expire    string `protobuf:"bytes,2,opt,name=expire,proto3" json:"expire,omitempty"`
}

func (x *TaskNotificationDeleteAccountAfter24Hours) Reset() {
	*x = TaskNotificationDeleteAccountAfter24Hours{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_outgoing_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskNotificationDeleteAccountAfter24Hours) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskNotificationDeleteAccountAfter24Hours) ProtoMessage() {}

func (x *TaskNotificationDeleteAccountAfter24Hours) ProtoReflect() protoreflect.Message {
	mi := &file_event_outgoing_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskNotificationDeleteAccountAfter24Hours.ProtoReflect.Descriptor instead.
func (*TaskNotificationDeleteAccountAfter24Hours) Descriptor() ([]byte, []int) {
	return file_event_outgoing_proto_rawDescGZIP(), []int{15}
}

func (x *TaskNotificationDeleteAccountAfter24Hours) GetAccountID() uint64 {
	if x != nil {
		return x.AccountID
	}
	return 0
}

func (x *TaskNotificationDeleteAccountAfter24Hours) GetExpire() string {
	if x != nil {
		return x.Expire
	}
	return ""
}

type AccountVerifiedDelete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountID uint64 `protobuf:"varint,1,opt,name=accountID,proto3" json:"accountID,omitempty"`
}

func (x *AccountVerifiedDelete) Reset() {
	*x = AccountVerifiedDelete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_outgoing_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountVerifiedDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountVerifiedDelete) ProtoMessage() {}

func (x *AccountVerifiedDelete) ProtoReflect() protoreflect.Message {
	mi := &file_event_outgoing_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountVerifiedDelete.ProtoReflect.Descriptor instead.
func (*AccountVerifiedDelete) Descriptor() ([]byte, []int) {
	return file_event_outgoing_proto_rawDescGZIP(), []int{16}
}

func (x *AccountVerifiedDelete) GetAccountID() uint64 {
	if x != nil {
		return x.AccountID
	}
	return 0
}

type SyncDeactivateAccountMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *SyncDeactivateAccountMessage) Reset() {
	*x = SyncDeactivateAccountMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_outgoing_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncDeactivateAccountMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDeactivateAccountMessage) ProtoMessage() {}

func (x *SyncDeactivateAccountMessage) ProtoReflect() protoreflect.Message {
	mi := &file_event_outgoing_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDeactivateAccountMessage.ProtoReflect.Descriptor instead.
func (*SyncDeactivateAccountMessage) Descriptor() ([]byte, []int) {
	return file_event_outgoing_proto_rawDescGZIP(), []int{17}
}

func (x *SyncDeactivateAccountMessage) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SyncDeactivateAccountMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type SyncDeletedAccountToLoyalty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email  string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *SyncDeletedAccountToLoyalty) Reset() {
	*x = SyncDeletedAccountToLoyalty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_outgoing_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncDeletedAccountToLoyalty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDeletedAccountToLoyalty) ProtoMessage() {}

func (x *SyncDeletedAccountToLoyalty) ProtoReflect() protoreflect.Message {
	mi := &file_event_outgoing_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDeletedAccountToLoyalty.ProtoReflect.Descriptor instead.
func (*SyncDeletedAccountToLoyalty) Descriptor() ([]byte, []int) {
	return file_event_outgoing_proto_rawDescGZIP(), []int{18}
}

func (x *SyncDeletedAccountToLoyalty) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SyncDeletedAccountToLoyalty) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

var File_event_outgoing_proto protoreflect.FileDescriptor

var file_event_outgoing_proto_rawDesc = []byte{
	0x0a, 0x14, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2d, 0x6f, 0x75, 0x74, 0x67, 0x6f, 0x69, 0x6e, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x46, 0x0a,
	0x10, 0x53, 0x79, 0x6e, 0x63, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x79, 0x0a, 0x15, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a,
	0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x22, 0x89, 0x01, 0x0a, 0x13, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x42, 0x79, 0x54, 0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x74, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x65, 0x6c,
	0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x22, 0xd6, 0x04, 0x0a,
	0x0e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x74, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x6f, 0x62, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x6f, 0x62, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72,
	0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x61, 0x72, 0x64, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x61, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x63, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x0e, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x65, 0x6c, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x65, 0x64, 0x18, 0x10, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x74, 0x65, 0x6c, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x11, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x12, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x18, 0x13, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f,
	0x6e, 0x65, 0x49, 0x44, 0x18, 0x15, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x6e, 0x65, 0x49,
	0x44, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x16, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x17, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0xd6, 0x04, 0x0a, 0x0e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x74, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x65, 0x6c,
	0x12, 0x10, 0x0a, 0x03, 0x64, 0x6f, 0x62, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64,
	0x6f, 0x62, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x77, 0x61, 0x72, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x61,
	0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69,
	0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x0f,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x20, 0x0a, 0x0b,
	0x74, 0x65, 0x6c, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x10, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0b, 0x74, 0x65, 0x6c, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x24,
	0x0a, 0x0d, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18,
	0x11, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18,
	0x12, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x13, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67,
	0x75, 0x61, 0x67, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67,
	0x75, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x6e, 0x65, 0x49, 0x44, 0x18, 0x15, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x6e, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x18, 0x16, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x17,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3b,
	0x0a, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x65, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x65, 0x6c, 0x22, 0x3d, 0x0a, 0x0d, 0x50,
	0x68, 0x6f, 0x6e, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x65, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x65, 0x6c, 0x22, 0x49, 0x0a, 0x0f, 0x4c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x22, 0x76, 0x0a, 0x16, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x42, 0x79, 0x54, 0x65, 0x6c, 0x12,
	0x1a, 0x0a, 0x08, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x74,
	0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x65, 0x6c, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x22, 0x2c, 0x0a,
	0x0e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x22, 0x3a, 0x0a, 0x1a, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x32, 0x0a, 0x12, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x44, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x30, 0x0a, 0x10, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x4e, 0x0a,
	0x16, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x22, 0x60, 0x0a,
	0x28, 0x54, 0x61, 0x73, 0x6b, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x66,
	0x74, 0x65, 0x72, 0x33, 0x30, 0x44, 0x61, 0x79, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x22,
	0x61, 0x0a, 0x29, 0x54, 0x61, 0x73, 0x6b, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x41, 0x66, 0x74, 0x65, 0x72, 0x32, 0x34, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x12, 0x1c, 0x0a, 0x09,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x22, 0x35, 0x0a, 0x15, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x69, 0x65, 0x64, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x48, 0x0a, 0x1c, 0x53, 0x79, 0x6e,
	0x63, 0x44, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x22, 0x4b, 0x0a, 0x1b, 0x53, 0x79, 0x6e, 0x63, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x6f, 0x4c, 0x6f, 0x79, 0x61, 0x6c,
	0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x42, 0x0c, 0x48, 0x02, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_event_outgoing_proto_rawDescOnce sync.Once
	file_event_outgoing_proto_rawDescData = file_event_outgoing_proto_rawDesc
)

func file_event_outgoing_proto_rawDescGZIP() []byte {
	file_event_outgoing_proto_rawDescOnce.Do(func() {
		file_event_outgoing_proto_rawDescData = protoimpl.X.CompressGZIP(file_event_outgoing_proto_rawDescData)
	})
	return file_event_outgoing_proto_rawDescData
}

var file_event_outgoing_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_event_outgoing_proto_goTypes = []interface{}{
	(*SyncAccountEvent)(nil),                          // 0: proto.SyncAccountEvent
	(*AccountCreatedByEmail)(nil),                     // 1: proto.AccountCreatedByEmail
	(*AccountCreatedByTel)(nil),                       // 2: proto.AccountCreatedByTel
	(*AccountCreated)(nil),                            // 3: proto.AccountCreated
	(*AccountUpdated)(nil),                            // 4: proto.AccountUpdated
	(*PhoneLinked)(nil),                               // 5: proto.PhoneLinked
	(*PhoneVerified)(nil),                             // 6: proto.PhoneVerified
	(*LanguageUpdated)(nil),                           // 7: proto.LanguageUpdated
	(*AccountRegisteredByTel)(nil),                    // 8: proto.AccountRegisteredByTel
	(*AccountDeleted)(nil),                            // 9: proto.AccountDeleted
	(*AccountDeactivateRequested)(nil),                // 10: proto.AccountDeactivateRequested
	(*AccountDeactivated)(nil),                        // 11: proto.AccountDeactivated
	(*AccountActivated)(nil),                          // 12: proto.AccountActivated
	(*TaskDeactivatedAccount)(nil),                    // 13: proto.TaskDeactivatedAccount
	(*TaskNotificationDeleteAccountAfter30Days)(nil),  // 14: proto.TaskNotificationDeleteAccountAfter30Days
	(*TaskNotificationDeleteAccountAfter24Hours)(nil), // 15: proto.TaskNotificationDeleteAccountAfter24Hours
	(*AccountVerifiedDelete)(nil),                     // 16: proto.AccountVerifiedDelete
	(*SyncDeactivateAccountMessage)(nil),              // 17: proto.SyncDeactivateAccountMessage
	(*SyncDeletedAccountToLoyalty)(nil),               // 18: proto.SyncDeletedAccountToLoyalty
}
var file_event_outgoing_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_event_outgoing_proto_init() }
func file_event_outgoing_proto_init() {
	if File_event_outgoing_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_event_outgoing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncAccountEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_outgoing_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountCreatedByEmail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_outgoing_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountCreatedByTel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_outgoing_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountCreated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_outgoing_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountUpdated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_outgoing_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhoneLinked); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_outgoing_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhoneVerified); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_outgoing_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LanguageUpdated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_outgoing_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountRegisteredByTel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_outgoing_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountDeleted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_outgoing_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountDeactivateRequested); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_outgoing_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountDeactivated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_outgoing_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountActivated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_outgoing_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskDeactivatedAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_outgoing_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskNotificationDeleteAccountAfter30Days); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_outgoing_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskNotificationDeleteAccountAfter24Hours); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_outgoing_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountVerifiedDelete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_outgoing_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncDeactivateAccountMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_outgoing_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncDeletedAccountToLoyalty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_event_outgoing_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_outgoing_proto_goTypes,
		DependencyIndexes: file_event_outgoing_proto_depIdxs,
		MessageInfos:      file_event_outgoing_proto_msgTypes,
	}.Build()
	File_event_outgoing_proto = out.File
	file_event_outgoing_proto_rawDesc = nil
	file_event_outgoing_proto_goTypes = nil
	file_event_outgoing_proto_depIdxs = nil
}
